table Mesures
	lineageTag: d8f4328f-5ca0-44d9-a28e-291f049a1bc7

	measure 'Quantity Item Total' =
			
			CALCULATE(
			    SUM(orders_items[order_item_quantity]),
			    FILTER(Orders, Orders[order_status] <> "CANCELED")
			)
		formatString: 0
		lineageTag: 62029fcb-36f5-4080-96d4-c4996ff5da95

	measure 'Total Sales' =
			
			CALCULATE(
			    SUM(orders_items[order_item_subtotal]),
			    FILTER(Orders, Orders[order_status] <> "CANCELED")
			)
		lineageTag: e18eb1b9-4ad3-400f-861e-6b57ccbc9e5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales LY' = ```
			CALCULATE([Total Sales],SAMEPERIODLASTYEAR('Calendar'[Date])) 
			```
		lineageTag: 358c1b45-3b39-4ca4-89ec-1b355736d788

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity LY' = ```
			CALCULATE([Quantity Item Total],SAMEPERIODLASTYEAR('Calendar'[Date])) 
			```
		formatString: 0
		lineageTag: 1a834c8c-0225-4ca4-94b2-560fe691d61e

	partition Mesures = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

